import { FaEdge, FaFirefoxBrowser, FaSafari } from "react-icons/fa";
import { FcGoogle } from "react-icons/fc";
import { cn } from "../lib/utils";
// from personal repo: github.com/kanakkholwal/kanakkholwal
import {
	PiArrowClockwiseDuotone,
	PiArrowCounterClockwiseDuotone,
	PiArrowDownRight,
	PiArrowLeftDuotone,
	PiArrowRightDuotone,
	PiArrowUpDuotone,
	PiArrowUpRightDuotone,
	PiArrowsDownUp,
	PiArticleDuotone,
	PiBellDuotone,
	PiBookOpenDuotone,
	PiBookmarkSimpleDuotone,
	PiBroadcastDuotone,
	PiBrowserDuotone,
	PiBugBeetleDuotone,
	PiCalendarBlankDuotone,
	PiCameraDuotone,
	PiCaretDownBold,
	PiCaretLeft,
	PiCaretRight,
	PiCaretRightBold,
	PiChartBarDuotone,
	PiChartLineUpDuotone,
	PiChartPieDuotone,
	PiChatsDuotone,
	PiCheckBold,
	PiCheckCircleDuotone,
	PiCircleDuotone,
	PiCircleNotchDuotone,
	PiClipboardTextDuotone,
	PiClockAfternoonDuotone,
	PiClockCounterClockwiseDuotone,
	PiCodeDuotone,
	PiCommandDuotone,
	PiCopyDuotone,
	PiCpuDuotone,
	PiDeviceMobileDuotone,
	PiDevicesDuotone,
	PiDotsThreeOutline,
	PiDotsThreeVerticalDuotone,
	PiEyeDuotone,
	PiFacebookLogoDuotone,
	PiFileDocDuotone,
	PiFolderDuotone,
	PiFolderOpenDuotone,
	PiFunnel,
	PiGameControllerDuotone,
	PiGithubLogoDuotone,
	PiGlobeDuotone,
	PiGoogleChromeLogoDuotone,
	PiGoogleLogoDuotone,
	PiHeartDuotone,
	PiHouseDuotone,
	PiIdentificationBadgeDuotone,
	PiIdentificationCardDuotone,
	PiInfinityDuotone,
	PiInstagramLogoDuotone,
	PiLayoutDuotone,
	PiLightningDuotone,
	PiLinkedinLogoDuotone,
	PiListDuotone, // For TOC
	PiLockKeyDuotone,
	PiMagnifyingGlassDuotone,
	PiMailboxDuotone,
	PiMediumLogoDuotone,
	PiMicrophoneStageDuotone, // For Podcast
	PiMonitorDuotone,
	PiMoonDuotone,
	PiNotebookDuotone,
	PiPackageDuotone,
	PiPaletteDuotone,
	PiPaperPlaneRightDuotone, // For Send/Share
	PiPencilSimpleDuotone,
	PiPhoneDuotone,
	PiPlus,
	PiPlusCircleDuotone,
	PiPushPinDuotone,
	PiPushPinSlashDuotone,
	PiQuestionDuotone,
	PiRocketLaunchDuotone,
	PiScrollDuotone, // Fit for History/Experiences
	PiShareNetworkDuotone, // Fit for Share
	PiShieldCheckDuotone,
	PiSidebarDuotone,
	PiSidebarSimpleDuotone,
	PiSlidersHorizontalDuotone,
	PiSparkleDuotone,
	PiSpinner,
	PiStarDuotone,
	PiSunDuotone,
	PiTerminalWindowDuotone,
	PiTextAlignLeftDuotone,
	PiTrashDuotone,
	PiTrendUpDuotone,
	PiTwitterLogoDuotone,
	PiUserPlusDuotone,
	PiUserSoundDuotone,
	PiUsersDuotone,
	PiWarningCircleDuotone,
	PiWaveTriangleDuotone,
	PiXDuotone,
	PiXLogoDuotone, // For New Twitter (X)
	PiYoutubeLogoDuotone
} from "react-icons/pi";

export const IconComponent = {
	// --- General UI ---
	activity: PiWaveTriangleDuotone,
	barchart: PiChartBarDuotone,
	book: PiBookOpenDuotone,
	"identity-badge": PiIdentificationBadgeDuotone,
	"identity-card": PiIdentificationCardDuotone,
	"notebook": PiNotebookDuotone,
	"chats": PiChatsDuotone,
	trash: PiTrashDuotone,
	calendar: PiCalendarBlankDuotone,
	sparkles: PiSparkleDuotone,
	code: PiCodeDuotone,
	dot: PiCircleDuotone,
	eye: PiEyeDuotone,
	camera: PiCameraDuotone,
	gamepad2: PiGameControllerDuotone,
	palette: PiPaletteDuotone,
	zap: PiLightningDuotone,
	cpu: PiCpuDuotone,
	globe: PiGlobeDuotone,
	share: PiShareNetworkDuotone,
	lock: PiLockKeyDuotone,
	pencil: PiPencilSimpleDuotone,
	command: PiCommandDuotone,
	search: PiMagnifyingGlassDuotone,
	pin: PiPushPinDuotone,
	"pin-off": PiPushPinSlashDuotone,
	"trend-up": PiTrendUpDuotone,
	X: PiXDuotone,
	"align-left": PiTextAlignLeftDuotone,
	toc: PiListDuotone,
	"chart-bar-big": PiChartBarDuotone,
	"chart-candlestick": PiChartLineUpDuotone,
	"ellipsis-vertical": PiDotsThreeVerticalDuotone,
	layout: PiLayoutDuotone,
	default: PiLayoutDuotone,
	unknown: PiQuestionDuotone,
	"sliders-horizontal": PiSlidersHorizontalDuotone,
	"circle-check": PiCheckCircleDuotone,
	"rotate-ccw": PiArrowCounterClockwiseDuotone,
	"rotate-cw": PiArrowClockwiseDuotone,
	"check:bold": PiCheckBold,
	"person-speaking": PiUserSoundDuotone,
	infinity: PiInfinityDuotone,
	list: PiListDuotone,
	sidebar: PiSidebarDuotone,
	star: PiStarDuotone,
	bug: PiBugBeetleDuotone,
	circle: PiCircleNotchDuotone,
	"user-add": PiUserPlusDuotone,
	broadcast: PiBroadcastDuotone,
	// --- Content & Media ---
	articles: PiArticleDuotone,
	experiences: PiScrollDuotone, // Represents history/scroll
	podcast: PiMicrophoneStageDuotone,
	heart: PiHeartDuotone,
	"heart-empty": PiHeartDuotone, // Phosphor Duotone style is consistent
	"folder-open": PiFolderOpenDuotone,
	"folder": PiFolderDuotone,
	"chart-pie": PiChartPieDuotone,
	"house": PiHouseDuotone,
	// --- Devices & Browsers ---
	safari: FaSafari, // No Phosphor equivalent
	chrome: PiGoogleChromeLogoDuotone,
	firefox: FaFirefoxBrowser, // No Phosphor equivalent
	edge: FaEdge, // No Phosphor equivalent
	browser: PiBrowserDuotone,
	monitor: PiMonitorDuotone,
	smartphone: PiDeviceMobileDuotone,
	"monitor-smartphone": PiDevicesDuotone,
	website: PiGlobeDuotone,
	clock: PiClockAfternoonDuotone,
	"clock-ccw": PiClockCounterClockwiseDuotone,
	"bell": PiBellDuotone,

	// --- Actions ---
	copy: PiCopyDuotone,
	rocket: PiRocketLaunchDuotone,
	plus_circle: PiPlusCircleDuotone,
	"clipboard": PiClipboardTextDuotone, // Closer metaphor for "copied text"
	send: PiPaperPlaneRightDuotone,
	bookmark: PiBookmarkSimpleDuotone,
	"bookmark-check": PiCheckCircleDuotone,

	// --- Social & Communication ---
	facebook: PiFacebookLogoDuotone,
	youtube: PiYoutubeLogoDuotone,
	github: PiGithubLogoDuotone,
	instagram: PiInstagramLogoDuotone,
	linkedin: PiLinkedinLogoDuotone,
	mail: PiMailboxDuotone,
	phone: PiPhoneDuotone,
	shield: PiShieldCheckDuotone,
	terminal: PiTerminalWindowDuotone,
	twitter: PiXLogoDuotone,
	medium: PiMediumLogoDuotone,
	"twitter-bird": PiTwitterLogoDuotone,
	google: PiGoogleLogoDuotone,
	"google:colored": FcGoogle,
	package: PiPackageDuotone,
	users: PiUsersDuotone,
	docs: PiFileDocDuotone,
	// --- Navigation & Status ---
	"arrow-up-right": PiArrowUpRightDuotone,
	"arrow-right": PiArrowRightDuotone,
	"arrow-left": PiArrowLeftDuotone,
	"arrow-up": PiArrowUpDuotone,
	"arrow-down-right": PiArrowDownRight,
	"loader-circle": PiCircleNotchDuotone,
	"alert-circle": PiWarningCircleDuotone,
	spinner: PiSpinner,
	plus: PiPlus,
	funnel: PiFunnel,
	"caret-left": PiCaretLeft,
	"caret-right": PiCaretRight,
	"caret-right:bold": PiCaretRightBold,
	"caret-down": PiCaretDownBold,
	"arrows-down-up": PiArrowsDownUp,
	"dots-three": PiDotsThreeOutline,

	"sidebar:simple": PiSidebarSimpleDuotone,
	// bodies
	moon: PiMoonDuotone,
	sun: PiSunDuotone,
};

export function Icon({ name, className }) {
	const Icon = IconComponent[name];
	if (!Icon) {
		return null;
	}
	return <Icon className={cn("inline-block", className)} />;
}
